services:
  backend:
    build:
      context: ./be
      dockerfile: ./Dockerfile
    image: backend
    volumes:
    - /home/user/data/:/data
    ports:
      - "3000:3000"
    restart: always
    networks:
      - app
  frontend:
    build:
      context: ./fe
      dockerfile: ./Dockerfile
    image: frontend
    ports:
      - "8080:8080"
    restart: always
    networks:
      - app

networks:
  app:
    driver: bridge
